Document: triplegeo-service
Title: Debian triplegeo-service Manual
Author: <insert document author here>
Abstract: This manual describes what triplegeo-service is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/triplegeo-service/triplegeo-service.sgml.gz

Format: postscript
Files: /usr/share/doc/triplegeo-service/triplegeo-service.ps.gz

Format: text
Files: /usr/share/doc/triplegeo-service/triplegeo-service.text.gz

Format: HTML
Index: /usr/share/doc/triplegeo-service/html/index.html
Files: /usr/share/doc/triplegeo-service/html/*.html
